[package]
name = "redis_simple"
version = "0.1.0"
authors = ["aodhneine <11488344+aodhneine@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
